### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by asoftlabai** [jadevaibhav/Brain-Tumor-Segmentation-using-Deep-Neural-networks#2]
Am runing finalcode. ipnyb its looking for pretrained models which are missing in folder shared, can you kindly share those files,
or if you guide how to run step by step the code any documentation if u share it would be great help

**Comment by Jithinpandu** [comment]
i also have the same issue did you solve it 
if done please help me 

> Am runing finalcode. ipnyb its looking for pretrained models which are missing in folder shared, can you kindly share those files,
> or if you guide how to run step by step the code any documentation if u share it would be great help

**Comment by motahareaghalari** [comment]
Hello,
i also have the same issue did you solve it
if done please help me please.

**Comment by Rohithmarktricks** [comment]
Hello, 
I have the same issue. Do you have any documentation for the code? Thanks

**Comment by jadevaibhav** [comment]
Hello everyone,

Sorry for the delayed reply. I cannot share pre-trained model as mentioned on readme. You can use the code to train your own model.

**Comment by vishwajeetguptaiitbhu** [comment]
Hello,
Please can you share your code in arranged manner
