### ISSUE TITLE
Code is not in arranged manner

### ISSUE THREAD

**Issue by freakedmind** [jadevaibhav/Brain-Tumor-Segmentation-using-Deep-Neural-networks#3]
Hey,
please, can you share your code in an arranged manner? I'm not able to understand with that code.
Please share with me in an arranged manner.
Thank you

**Comment by jadevaibhav** [comment]
Hello,

Working on jupyter notebook lead to unorganised code, sorry about that. If you could refer to FinalCode.ipynb, I have put all the code in logical sequential manner.

Hope this helps.
